### ISSUE TITLE
Add language: Spanish

### ISSUE THREAD

**Issue by AlganOngun** [muhammeterenunlu/Mepros#15]
Directions:
1) Use en.js as a template (make a copy of en.js and rename it to be es.js)
2) Make another button with spanish flag under the button with Turkish
3) reference the script on the very top of html with defer attribute:
`<script defer src="Languages/es.js"></script>`
4) in languageHandler declare and implement a changeLanguageToSpanish() function (use other changeLanguageFunctions as a template)
5) call changeLanguageToSpanish() from spanish button onclick event in the html file
6) Do the actual translation in es.js file

Any other language can be added this way

**Comment by muhammeterenunlu** [comment]
Closed
